app:
  security:
    jwt:
      secret: bp1E1VL6y4mMMfmJO9sgkqfZA7xbPgBLS415x5FEizE=
      issuer: practica
      ttlMillis: 3600000
spring:
  main:
    allow-circular-references: false
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: false
    properties:
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate.format_sql: false
logging:
  level:
    root: WARN
    com.martzatech.vdhg.crmprojectback: INFO